import sqlite3

conn = sqlite3.connect('tft.db')
c = conn.cursor()

champions = [
    (1, 'Annie', 1),
    (2, 'Corki', 1),
    (3, 'Evelynn', 1),
    (4, 'Jinx', 1),
    (5, 'Kennen', 1),
    (6, 'KSante', 1),
    (7, 'Lillia', 1),
    (8, 'Nami', 1),
    (9, 'Olaf', 1),
    (10, 'Taric', 1),
    (11, 'Tahm Kench', 1),
    (12, 'Vi', 1),
    (13, 'Yasuo', 1),
    (14, 'Aphelios', 2),
    (15, 'Bard', 2),
    (16, 'Garen', 2),
    (17, 'Gnar', 2),
    (18, 'Gragas', 2),
    (19, 'Jax', 2),
    (20, 'KaiSa', 2),
    (21, 'Katarina', 2),
    (22, 'Kayle', 2),
    (23, 'Pantheon', 2),
    (24, 'Senna', 2),
    (25, 'Seraphine', 2),
    (26, 'Twitch', 2),
    (27, 'Amumu', 3),
    (28, 'Ekko', 3),
    (29, 'Lulu', 3),
    (30, 'Lux', 3),
    (31, 'Miss Fortune', 3),
    (32, 'Mordekaiser', 3),
    (33, 'Neeko', 3),
    (34, 'Riven', 3),
    (35, 'Samira', 3),
    (36, 'Sett', 3),
    (37, 'Urgot', 3),
    (38, 'Vex', 3),
    (39, 'Yone', 3),
    (40, 'Ahri', 4),
    (41, 'Akali 1', 4),
    (42, 'Akali 2', 4),
    (43, 'Blitzcrank', 4),
    (44, 'Caitlyn', 4),
    (45, 'Ezreal', 4),
    (46, 'Karthus', 4),
    (47, 'Poppy', 4),
    (48, 'Thresh', 4),
    (49, 'Twisted Fate', 4),
    (50, 'Viego', 4),
    (51, 'Zac', 4),
    (52, 'Zed', 4),
    (53, 'Illaoi', 5),
    (54, 'Jhin', 5),
    (55, 'Kayn', 5),
    (56, 'Lucian', 5),
    (57, 'Qiyana', 5),
    (58, 'Sona', 5),
    (59, 'Yorick', 5),
    (60, 'Ziggs', 5)
]

c.executemany('INSERT INTO champion VALUES (?, ?, ?)', champions)

augments = [
    (1, 'Team Building', '9ArmyBuilding'),
    (2, 'Martyr', '9Martyr'),
    (3, 'Buried Treasures 1', '9BuildingACollection'),
    (4, 'Metabolic Accelerator', '6MetabolicAccelerator'),
    (5, 'You Have My Sword', '9YouHaveMySword'),
    (6, 'Rich Get Richer', '6RichGetRicher'),
    (7, 'Wellness Trust', '9MoneyHealsAllWounds'),
    (8, 'Pandoras Items 2', '9PandorasItems2'),
    (9, 'Cybernetic Uplink 2', '6CyberneticUplink2'),
    (10, 'Harmacist 1', '9Harmacist1'),
    (11, 'Patient Study', '9LearningFromExperience2'),
    (12, 'Live for Danger', '10LiveForDanger'),
    (13, 'Heavy Hitters', 'd'),
    (14, 'Infernal Contract', '9InfernalContract'),
    (15, 'Fully Adapted', '10FullyAdapted'),
    (16, 'Shopping Spree', '9HighEndSector'),
    (17, 'Silver Veil', '10SilverVeil'),
    (18, 'Pumping Up 1', '9PumpingUp'),
    (19, 'Heroic Presence', '10GuardianHeroicPresence'),
    (20, 'Good For Something 2', '10GoodForSomething'),
    (21, 'Unleashed Arcana', '9UnleashedArcana'),
    (22, 'Insert Coin', '10InsertCoin'),
    (23, 'Cybernetic Bulk 3', '9CyberneticBulk3'),
    (24, 'Latent Forge', '9LongTimeCrafting'),
    (25, 'Cybernetic Uplink 1', '6CyberneticUplink1'),
    (26, 'Missed Connections', '9MissedConnections'),
    (27, 'Bigger Shot', '10BiggerShot'),
    (28, 'Inspiring Epitaph', '10InspiringEpitaph'),
    (29, 'Going Long', '10GoingLong'),
    (30, 'Spoils of War 3', '9DravenSpoilsOfWar3'),
    (31, 'Stationary Support 3', '9StationarySupport3'),
    (32, 'Cutting Corners', '9CuttingCorners'),
    (33, 'Not Today', '9NotToday'),
    (34, 'Silver Ticket', '9BronzeTicket'),
    (35, 'Idealism', '9Idealism'),
    (36, 'Return On Investment', '9ReturnOnInvestment'),
    (37, 'Threes Company', '6ThreesCompany'),
    (38, 'Phreaky Friday +', '9PhreakyFridayPlus'),
    (39, 'Lucky Gloves+', '7LuckyGlovesPlus'),
    (40, 'Support Cache', '9SupportCache'),
    (41, 'Healing Orbs 1', '9HealingOrbsI'),
    (42, 'Metalheads', '10MetalHeads'),
    (43, 'Jeweled Lotus 2', '9JeweledLotus'),
    (44, 'What The Forge', '9WhatTheForge'),
    (45, 'Last Stand', '7LastStand'),
    (46, 'Pandoras Items', '6PandorasItems'),
    (47, 'Rolling For Days 1', '9Commander_RollingForDays'),
    (48, 'Trade Sector', '6TradeSector'),
    (49, 'Do It for the Fans', '10Superfan_ForTheFans'),
    (50, 'Shock Treatment', '10ShockTreatment'),
    (51, 'Impenetrable Bulwark', '9ImpenetrableBulwark'),
    (52, 'Submit to the Pit', '10SubmitToThePit'),
    (53, 'Prismatic Ticket', '6GachaAddict'),
    (54, 'Switching Gears', '10SwitchingGears'),
    (55, 'Cybernetic Bulk 1', '9CyberneticBulk1'),
    (56, 'Iron Assets', '9IronAssets'),
    (57, 'Emotional Connection', '10EmotionalConnection'),
    (58, 'Blank Slate', '10BlankSlate'),
    (59, 'New Recruit', '6ForceOfNature'),
    (60, 'Pandoras Items 3', '9PandorasRadiantBox'),
    (61, 'Balanced Budget', '9BalancedBudget2'),
    (62, 'Young and Wild and Free', '9YoungAndWildAndFree'),
    (63, 'Harmacist 2', '9Harmacist2'),
    (64, 'Consistency', '7Consistency'),
    (65, 'A Cut Above', '9ACutAbove'),
    (66, 'Magic Wand', '9OldMansWalkingStick'),
    (67, 'Stars are Born', '9StarsAreBorn'),
    (68, 'Endless Hordes', '9OneHundredDuckSizedHorses'),
    (69, 'Lucky Gloves', '7LuckyGloves'),
    (70, 'Portable Forge++', '6PortableForgePlusPlus'),
    (71, 'Best Friends 1', '7BestFriends1'),
    (72, 'Threes a Crowd', '9ThreesACrowd'),
    (73, 'Ascension', '9Commander_Ascension'),
    (74, 'Starter Kit', '9StarterKit'),
    (75, 'Salvage Bin+', '8SalvageBinPlus'),
    (76, 'Lategame Specialist', '7LategameSpecialist'),
    (77, 'Vampirism 1', '10Vampirism'),
    (78, 'Spoils of War 2', '9DravenSpoilsOfWar2'),
    (79, 'Thats Jazz, Baby', '10ThatsJazzBaby'),
    (80, 'Crown Guarded', '10CrownGuarded'),
    (81, 'Level Up!', '6MaxLevel10'),
    (82, 'Heartthrobs', '10HeartCollector'),
    (83, 'Roll The Dice', '9RollTheDice'),
    (84, 'Recombobulator', '6Recombobulator'),
    (85, 'Indomitable Will', '9IndomitableWill'),
    (86, 'Component Buffet', '9CustomerIsAlwaysRight'),
    (87, 'Scrappy Inventions', '9ImpromptuInventions'),
    (88, 'Lucky Streak', '10LuckyStreak'),
    (89, 'Hedge Fund', '9HedgeFund'),
    (90, 'Cursed Crown', '7CursedCrown'),
    (91, 'Radiant Relics', '6RadiantRelics'),
    (92, 'Risky Moves', '9RiskyMoves'),
    (93, 'Infusion', '9Infusion'),
    (94, 'One, Two, Five!', '6OneTwoFive'),
    (95, 'Frequent Flier', '9JustKeepRolling'),
    (96, 'You Have My Bow', '9YouHaveMyBow'),
    (97, 'Hedge Fund++', '9HedgeFundPlusPlus'),
    (98, 'Final Reserves', '9FinalReserves'),
    (99, 'Tiniest Titan+', '9TiniestTitanPlus'),
    (100, 'Teaming Up 2', '9Commander_TeamingUp2'),
    (101, 'Blistering Strikes', '9RedBuff'),
    (102, 'Two Healthy', '9TwoHealthy'),
    (103, 'Combat Caster', '9CombatCaster'),
    (104, 'Pumping Up 2', '9PumpingUp2'),
    (105, 'Living Forge', '7LivingForge'),
    (106, 'What Doesnt Kill You', '9WhatDoesntKillYou'),
    (107, 'Double the Funk', '10DoubleTheFunk'),
    (108, 'Cybernetic Bulk 2', '9CyberneticBulk2'),
    (109, 'Keepers 1', '6Keepers1'),
    (110, 'Sleight of Hand', '9Sleightofhand'),
    (111, 'The Ol Razzle Dazzle', '10Bedazzled'),
    (112, 'Low Interest Rates', '10LowInterestRates'),
    (113, 'Jeweled Lotus 3', '9GreaterJeweledLotus'),
    (114, 'Expose Weakness', '10Executioner_ExposeWeakness'),
    (115, 'Cybernetic Uplink 3', '6CyberneticUplink3'),
    (116, 'Parting Gifts', '9DangerousToGoAlone'),
    (117, 'Portable Forge+', '6PortableForgePlus'),
    (118, 'Unified Resistance', '9Formation1'),
    (119, 'Tiny Titans', '6TinyTitans'),
    (120, 'Cluttered Mind', '7ClutteredMind'),
    (121, 'Keepers 2', '6Keepers2'),
    (122, 'The Golden Egg', '6TheGoldenEgg'),
    (123, 'Blinged Out', '10BlingedOut'),
    (124, 'Harmacist 3', '9Harmacist3'),
    (125, 'Stimpack', '10Stimpack'),
    (126, 'Tons of Stats!', '9TonsOfStats'),
    (127, 'On a Roll', '9OnARoll'),
    (128, 'Gargantuan Resolve', '9GargantuanResolve'),
    (129, 'Learning to Spell', '10LearningToSpell'),
    (130, 'Hedge Fund+', '9HedgeFundPlus'),
    (131, 'Cruel Pact', '7SacrificialPact'),
    (132, 'Tiniest Titan', '9TiniestTitan'),
    (133, 'Twin Terror 2', '10TwinTerror2'),
    (134, 'Stationary Support', '9StationarySupport2'),
    (135, 'Item Grab Bag 1', '6ItemGrabBag1'),
    (136, 'Escort Quest', '9EscortQuest'),
    (137, 'Talent Search', '10TalentSearch'),
    (138, 'Buried Treasures 2', '9BuildingACollectionPlus'),
    (139, 'Phreaky Friday', '9PhreakyFriday'),
    (140, 'Contagion', '9Contagion'),
    (141, 'Big Grab Bag', '9BigGrabBag'),
    (142, 'Sticks And Stones', '10SticksAndStones'),
    (143, 'Silver Ticket', '9SilverTicket'),
    (144, 'Too Big to Fail', '10TooBigToFail'),
    (145, 'Little Buddies', '10LittleBuddies'),
    (146, 'Buried Treasures 3', '9BuildingACollectionPlusPlus'),
    (147, 'Extended Play', '10RepetitiveRiffing'),
    (148, 'Portable Forge', '6PortableForge'),
    (149, 'Stationary Support 1', '9StationarySupport1'),
    (150, 'Caretakers Ally', '9BardPlaybook1'),
    (151, 'Best Friends 2', '7BestFriends2'),
    (152, 'Blinding Speed', '9BlindingSpeed'),
    (153, 'Bounty Hunters', '10Country_BountyHunters'),
    (154, 'Determined Investors', '10Determinedinvestors'),
    (155, 'Blood Money', '9BloodMoney'),
    (156, 'Gifts from the Fallen', '9GiftsFromTheFallen'),
    (157, 'Ones Twos Three', '9OneTwosThree'),
    (158, 'Big Gains', '10BigGains'),
    (159, 'Final Ascension', '9Commander_FinalAscension'),
    (160, 'March of Progress', '6SlowAndSteady'),
    (161, 'Reach the Summit', '10ReachTheSummit'),
    (162, 'Know Your Enemy', '9KnowYourEnemy'),
    (163, 'Partial Ascension', '9Commander_PartialAscension'),
    (164, 'Clear Mind', '6ClearMind'),
    (165, 'Remember Your Roots', '10RememberYourRoots'),
    (166, 'Rich Get Richer+', '6RichGetRicherPlus'),
    (167, 'Overwhelming Force', '9OverwhelmingForce'),
    (168, 'Caretakers Favor', '9BardPlaybook2'),
    (169, 'Unified Resistance 2', '9Formation2'),
    (170, 'Good For Something 1', '10GoodForSomethingSilver'),
    (171, 'Capricious Forge', '9CapriciousForge'),
    (172, 'Ramping Rhythm', '10RampingRhythm'),
    (173, 'Heroic Grab Bag', '10HeroicGrabBag'),
    (174, 'Caretakers Chosen', '9BardPlaybook3'),
    (175, 'Salvage Bin', '6SalvageBin'),
    (176, 'AFK', '7AFK'),
    (177, 'Teaming Up 1', '9Commander_TeamingUp1'),
    (178, 'Help Is On The Way', '10HelpIsOnTheWay'),
    (179, 'Raise the Tempo', '10SpellweaverHalftimeShow'),
    (180, 'Scapegoat', '10Scapegoat'),
    (181, 'Pumping Up 3', '9PumpingUp3'),
    (182, 'Long Distance Pals', '9LongDistanceRelationship2'),
    (183, 'Hologram', '10HeadlinerWoodlandCharm'),
    (184, 'Spoils of War 1', '9DravenSpoilsOfWar'),
    (185, 'Healing Orbs 2', '9HealingOrbsII'),
    (186, 'Silver Spoon', '9SilverSpoon'),
    (187, 'Crash Test Dummies', '10CrashTestDummies'),
    (188, 'Vampirism 2', '10VampirismPlus'),
    (189, 'Birthday Present', '7BirthdayPresents'),
    (190, 'Binary Airdrop', '6BinaryAirdrop'),
    (191, 'Twin Terror 1', '10TwinTerror1')
]

c.executemany('INSERT INTO augment VALUES (?, ?, ?)', augments)

conn.commit()

# Close the connection
conn.close()